import { defineConfig } from 'vitest/config';
import path from 'path';

export default defineConfig({
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      // src/db/index.ts imports Next.js's 'server-only' marker package (its
      // default export throws outside React Server Components). Route test
      // suites that exercise REAL handlers import '@/db', so alias the marker
      // to an empty module here; the plain-tsx path uses a Module._load
      // interception at the top of each test file instead (see the
      // executions/__tests__/route.test.ts harness).
      'server-only': path.resolve(__dirname, './src/lib/testing/server-only-stub.ts'),
    },
  },
  test: {
    // globals: true lets standalone assert-harness test files (e.g.
    // src/app/api/trades/__tests__/route.test.ts) register a vitest suite via
    // the synchronous `test` global — guarded by `typeof test !== 'undefined'`
    // — without a static vitest import, which would break their alternate
    // `npx tsx <file>` execution path. Regular vitest suites are unaffected
    // (they import from 'vitest' explicitly).
    globals: true,
    include: [
      'src/lib/account-lifecycle.test.ts',
      'src/lib/performance-pnl-scope.test.ts',
      'src/hooks/use-performance-pnl-scope.test.ts',
      'src/lib/workstation-view-types.test.ts',
      'src/lib/account-context.test.tsx',
      'src/lib/workstation-fixtures.test.ts',
      'src/lib/dash-ac-fixtures.test.ts',
      'src/components/workstation/workstation-context.test.tsx',
      'src/components/workstation/workstation-toolbar.test.tsx',
      'src/components/workstation/data-quality-alert-strip.test.tsx',
      'src/components/workstation/risk-positions-table.test.tsx',
      'src/components/workstation/risk-panel.test.tsx',
      'src/components/workstation/account-state-panel.test.tsx',
      'src/components/workstation/performance-panel.test.tsx',
      'src/components/workstation/process-review-panel.test.tsx',
      'src/components/workstation/workstation-view-switcher.test.tsx',
      'src/components/workstation/customize-bar.test.tsx',
      'src/components/workstation/workstation-keyboard-arrange.test.tsx',
      'src/components/workstation/workstation-arrange-grid.test.tsx',
      'src/components/workstation/trades-workspace-panel.test.tsx',
      'src/components/workstation/watchlist-panel.test.tsx',
      'src/lib/workstation-live-adapter.test.ts',
      'src/lib/account-defaults.test.ts',
      'src/app/api/settings/__tests__/route.default-eligibility.test.ts',
      'src/lib/readiness.test.ts',
      'src/lib/restore.test.ts',
      'src/db/__tests__/run-migrations.test.ts',
      'src/lib/__tests__/error-utils.test.ts',
      'src/lib/__tests__/execution-readiness.test.ts',
      'src/lib/__tests__/execution-equity.test.ts',
      'src/lib/__tests__/chart-palette.test.ts',
      'src/lib/__tests__/design-system-docs.test.ts',
      'src/lib/__tests__/workstation-docs.test.ts',
      'src/lib/__tests__/live-historical-contract.test.ts',
      'src/lib/__tests__/workstation-architecture-safety.test.ts',
      'src/lib/__tests__/trade-detail-docs.test.ts',
      'src/lib/__tests__/token-structure.test.ts',
      'src/lib/__tests__/surface-token-migration.test.ts',
      'src/lib/__tests__/execution-idempotency-migration.test.ts',
      'src/lib/__tests__/use-trade-detail-account-reconciliation.test.ts',
      'src/lib/__tests__/workflow-phase.test.ts',
      'src/lib/__tests__/risk-propagation-s05.test.ts',
      'src/app/api/trades/__tests__/workflow-phase.test.ts',
      'src/lib/__tests__/trade-execution-engine.test.ts',
      'src/lib/trade-correction-lifecycle.test.ts',
      'src/lib/__tests__/scorecard.test.ts',
      'src/lib/__tests__/performance-view-types.test.ts',
      'src/lib/__tests__/performance-kpi-catalogue.test.ts',
      'src/lib/__tests__/performance-close-date.test.ts',
      'src/lib/__tests__/performance-chart-options.test.ts',
      'src/app/api/app-profile/__tests__/route.test.ts',
      'src/app/api/readiness/__tests__/route.test.ts',
      'src/app/api/ai-settings/__tests__/route.test.ts',
      'src/app/api/trades/__tests__/execute.test.ts',
      'src/app/api/trades/__tests__/check-results.test.ts',
      'src/app/api/trades/__tests__/route.test.ts',
      'src/app/api/trades/planned-risk-preview/__tests__/route.test.ts',
      'src/app/api/trades/[id]/execute/__tests__/route.test.ts',
      'src/app/api/trades/[id]/executions/__tests__/route.test.ts',
      'src/app/api/trades/[id]/executions/[execId]/correct/__tests__/route.test.ts',
      'src/app/api/trades/[id]/risk-snapshot/__tests__/route.test.ts',
      'src/app/api/trades/[id]/review/__tests__/route.test.ts',
      'src/app/api/health/__tests__/route.test.ts',
      'src/lib/__tests__/clickhouse-client.test.ts',
      'src/lib/__tests__/ai-provider.test.ts',
      'src/lib/__tests__/ai-settings-integration.test.ts',
      'src/lib/__tests__/assessment-engine.test.ts',
      'src/app/api/trades/[id]/__tests__/route.test.ts',
      'src/app/api/trades/[id]/assessments/__tests__/route.test.ts',
      'src/lib/__tests__/market-quote.test.ts',
      'src/lib/__tests__/scheduler.test.ts',
      'src/lib/__tests__/market-data-settings-migration.test.ts',
      'src/lib/__tests__/clickhouse-provider.test.ts',
      'src/app/api/market-data/settings/__tests__/route.test.ts',
      'src/app/api/market-data/enrich-profiles/__tests__/route.test.ts',
      'src/lib/__tests__/clickhouse-client-config.test.ts',
      'src/lib/__tests__/token-encryption.test.ts',
      'src/lib/__tests__/schwab-tokens-migration.test.ts',
      'src/lib/__tests__/schwab-auth.test.ts',
      'src/app/api/schwab/auth-url/__tests__/route.test.ts',
      'src/app/api/schwab/callback/__tests__/route.test.ts',
      'src/lib/__tests__/schwab-provider.test.ts',
      'src/lib/__tests__/analysis-config.test.ts',
      'src/app/api/schwab/status/__tests__/route.test.ts',
      'src/app/api/schwab/disconnect/__tests__/route.test.ts',
      'src/lib/__tests__/market-data-resolver.test.ts',
      'src/app/api/trades/mtm/refresh/__tests__/route.vitest.test.ts',
      'src/app/api/trades/mtm/refresh/__tests__/pipeline-integration.test.ts',
      'src/lib/__tests__/backup-restore-table-consistency.test.ts',
      'src/lib/__tests__/profile-enricher.test.ts',
      'src/app/api/trades/[id]/mtm/__tests__/post.vitest.test.ts',
      'src/app/api/watchlist/prices/__tests__/route.test.ts',
      'src/app/api/watchlist/ohlc/__tests__/route.test.ts',
      'src/app/api/watchlist/__tests__/route.test.ts',
      'src/app/api/watchlist/[id]/__tests__/route.test.ts',
      'src/lib/alert-engine.test.ts',
      'src/lib/alert-polling.test.ts',
      'src/hooks/use-visibility-polling.test.ts',
      'src/hooks/use-customization-mode.test.ts',
      'src/hooks/use-chart-resize.test.ts',
      'src/hooks/use-chart-palette.test.tsx',
      'src/hooks/use-workstation-views.test.ts',
      'src/hooks/use-customize-mode.test.ts',
      'src/hooks/__tests__/use-performance-dashboards.test.ts',
      'src/hooks/__tests__/use-performance-dashboard.test.tsx',
      'src/hooks/__tests__/use-performance-instances.test.tsx',
      'src/types/dashboard-view.test.ts',
      'src/lib/accounting/decimal.test.ts',
      'src/lib/accounting/__tests__/economic-action.test.ts',
      'src/lib/accounting/__tests__/cash-direction-repair.test.ts',
      'src/lib/accounting/__tests__/activity-economic-direction.test.ts',
      'src/lib/accounting/__tests__/fee-repair.test.ts',
      'src/lib/accounting/legacy-migration.test.ts',
      'src/lib/accounting/legacy-migration-runner.test.ts',
      'src/lib/accounting/posting.test.ts',
      'src/lib/accounting/rebuild.test.ts',
      'src/lib/accounting/__tests__/accounting-integration.test.ts',
      'src/app/api/accounts/[id]/financial-events/__tests__/route.test.ts',
      'src/lib/accounting/__tests__/opening-balance-flow.test.ts',
      'src/lib/accounting/__tests__/financial-event-contracts.test.ts',
      'src/lib/accounting/__tests__/financial-event-posting.test.ts',
      'src/lib/accounting/__tests__/activity-rebuild.test.ts',
      'src/lib/accounting/__tests__/financial-events-integration.test.ts',
      'src/lib/accounting/__tests__/usd-currency-contract.test.ts',
      'src/lib/accounting/__tests__/financial-event-posting-atomicity.test.ts',
      'src/lib/accounting/__tests__/account-initialization.test.ts',
      'src/lib/testing/__tests__/test-db.test.ts',
      'src/app/api/accounts/[id]/initialize/__tests__/route.test.ts',
      'src/lib/accounting/__tests__/execution-contracts.test.ts',
      'src/lib/positions/fifo.test.ts',
      'src/lib/positions/rebuild.test.ts',
      'src/lib/accounting/__tests__/execution-posting.integration.test.ts',
      'src/app/api/accounts/[id]/executions/__tests__/route.test.ts',
      'src/app/api/accounts/[id]/executions/__tests__/a5-economic-action.test.ts',
      'src/app/api/accounts/[id]/executions/__tests__/a7-atomicity.test.ts',
      'src/app/api/accounts/[id]/positions/__tests__/route.test.ts',
      'src/lib/performance/valuation.test.ts',
      'src/lib/performance/performance.test.ts',
      'src/lib/performance/performance-rebuild.test.ts',
      'src/app/api/accounts/[id]/valuations/__tests__/route.test.ts',
      'src/app/api/accounts/[id]/performance/__tests__/route.test.ts',
      'src/lib/accounting/correction.test.ts',
      'src/lib/accounting/financial-event-correction.test.ts',
      'src/lib/accounting/ledger.test.ts',
      'src/app/api/accounts/[id]/executions/[executionId]/correct/__tests__/route.test.ts',
      'src/app/api/accounts/[id]/executions/[executionId]/correct/__tests__/a8-atomicity.test.ts',
      'src/app/api/accounts/[id]/financial-events/[eventId]/correct/__tests__/route.test.ts',
      'src/lib/accounting/reconciliation.test.ts',
      'src/app/api/accounts/[id]/reconciliation/__tests__/route.test.ts',
      'src/app/api/accounts/[id]/migration/__tests__/route.test.ts',
      'src/lib/accounting/dashboard-v2.test.ts',
      'src/lib/accounting/__tests__/dashboard-journal-linked.test.ts',
      'src/lib/accounting/__tests__/dashboard-journal-reconciliation.test.ts',
      'src/lib/accounting/__tests__/dashboard-snapshot-contract.test.ts',
      'src/lib/accounting/__tests__/freshness-policy.test.ts',
      'src/lib/accounting/__tests__/cross-system-integrity.test.ts',
      'src/lib/accounting/__tests__/cross-cutting-integrity.test.ts',
      'src/lib/accounting/__tests__/accounting-invariant-matrix.test.ts',
      'src/lib/accounting/__tests__/repair-alias-executions.test.ts',
      'src/lib/accounting/__tests__/account-transactions-writer-guard.test.ts',
      'src/app/api/dashboard/v2/__tests__/route.test.ts',
      'src/app/api/performance/analytics/__tests__/route.test.ts',
      'src/app/(legacy)/settings/workspace/__tests__/page.test.tsx',
      'src/app/(legacy)/settings/risk-defaults/__tests__/page.test.tsx',
      'src/app/(trades)/trades/__tests__/page.test.tsx',
      'src/app/(legacy)/trades/new/page.test.tsx',
      'src/app/(trades)/trades/__tests__/actions-propagation.test.tsx',
      'src/app/(trades)/trades/__tests__/scratch-action.test.tsx',
      'src/app/(trades)/trades/__tests__/distance-columns.test.ts',
      'src/app/(trades)/trades/__tests__/phase-column.test.tsx',
      'src/components/trade-detail/__tests__/planned-phase-view-scratch.test.tsx',
      'src/components/trade-detail/__tests__/add-fill-dialog.test.tsx',
      'src/components/trade-detail/__tests__/trade-detail-header.test.tsx',

      'src/components/dashboard/dashboard-widget.test.tsx',

      'src/components/dashboard/__tests__/chart-palette-migration.test.ts',
      'src/components/dashboard/formatting.test.ts',
      'src/lib/trade-formatters.test.tsx',

      'src/components/dashboard/equity-drawdown-chart.test.tsx',
      'src/components/dashboard/monthly-performance-chart.test.tsx',

      'src/components/dashboard/r-distribution-chart.test.tsx',
      'src/components/dashboard/directional-performance-widget.test.tsx',
      'src/components/dashboard/calendar-heatmap-widget.test.tsx',
      'src/components/dashboard/period-matrix-widget.test.tsx',
      'src/components/dashboard/setup-ranking-widget.test.tsx',
      'src/components/dashboard/process-discipline-widget.test.tsx',
      'src/components/dashboard/attention-insights-widget.test.tsx',

      'src/components/sidebar/nav-config.test.ts',
      'src/components/performance/__tests__/kpi-card.test.tsx',
      'src/components/performance/__tests__/kpi-row.test.tsx',
      'src/components/performance/__tests__/chart-grid.test.tsx',
      'src/components/performance/__tests__/chart-widget.test.tsx',
      'src/components/performance/__tests__/configure-dialog.test.tsx',
      'src/lib/__tests__/performance-widget-registry.test.ts',
      'src/components/performance/__tests__/performance-toolbar.test.tsx',
      'src/components/performance/__tests__/dashboard-switcher.test.tsx',
      'src/components/performance/__tests__/kpi-micro-viz.test.tsx',
      'src/components/performance/__tests__/performance-filter-bar.test.tsx',
      'src/components/performance/__tests__/widget-actions-menu.test.tsx',
      'src/components/accounting/account-correction-form.test.tsx',
      'src/components/accounting/financial-event-correction-dialog.test.tsx',
      'src/components/accounting/add-account-dialog.test.tsx',
      'src/components/accounting/account-initialization.test.tsx',
      'src/components/accounting/opening-balance-form.test.tsx',
      'src/components/accounting/account-overview.test.tsx',
      'src/components/accounting/financial-transaction-composer.test.tsx',
      'src/components/accounting/account-ledger.test.tsx',
      'src/components/accounting/account-positions.test.tsx',
      'src/components/accounting/account-reconciliation-summary.test.tsx',
      'src/components/accounting/account-settings.test.tsx',
      'src/components/edit-trade-dialog.test.tsx',
      'src/components/execute-dialog.test.tsx',
      'src/components/plan-trade-form.test.tsx',
      'src/app/api/accounts/[id]/__tests__/route.defaults.test.ts',
      'src/app/api/accounts/[id]/__tests__/route.test.ts',
      'src/app/api/accounts/[id]/close/__tests__/route.test.ts',
      'src/lib/account-detail.test.ts',
      'src/lib/__fixtures__/account-detail-contracts.test.ts',
      'src/app/api/accounts/[id]/overview/__tests__/route.test.ts',
      'src/app/api/accounts/[id]/ledger/__tests__/route.test.ts',
      'src/app/api/dashboard/views/__tests__/route.test.ts',
      'src/components/ui/__tests__/primitive-contracts.test.ts',
      'src/components/ui/badge.test.tsx',
      'scripts/journal.test.mjs',
      'scripts/__tests__/playwright-matrix-artifacts.test.ts',
    ],
    environment: 'jsdom',
  },
});
